---
title: "Parallel Computing"
format: html
editor: visual
---

## Parallel Computing Prac

### Question 1

```{r}
library(foreach)
library(kableExtra)

one <- as.data.frame( foreach(i = 1:100, .combine = rbind) %do%{
  samp <- rexp(100, 1)
  c(
  x_bar <- mean(samp),
  vari <- var(samp))
  #results = rbind(x_bar, vari)
}
)
kable(one,
      col.names = c("Sample Mean", "Sample Variance"))
```

### Question 2

```{r}
library(doParallel)
library(MASS)

x <- galaxies
n <- length(x)
B <- 200000

# Serial Bootstrap
t_serial <- system.time({
  med_serial <- replicate(B, median(sample(x, n, replace = TRUE)))
})["elapsed"]

t_serial

# One Bootstrap per task (in parallel)

cl <- makeCluster(detectCores() - 1) # do not want my computer to crashhhhhh
registerDoParallel(cl)

t_par_single <- system.time({
  med_par_single <- foreach(i = 1:B, .combine = c) %dopar% {
    median(sample(x, n, replace = TRUE))
  }
})["elapsed"]

stopCluster(cl)
t_par_single #MUCH SLOWER


# 1000 Bootstraps per task
chunk_size <- 1000
nchunks <- 200

cl <- makeCluster(detectCores() - 1)
registerDoParallel(cl)

t_par_chunk <- system.time({
  med_par_chunk <- foreach(k = 1:nchunks, .combine = c) %dopar% {
    m <- if (k < nchunks) chunk_size else (B - (nchunks - 1) * chunk_size)
    replicate(m, median(sample(x, n, replace = TRUE)))
  }
})["elapsed"]

stopCluster(cl)

t_par_chunk # MUUUUCH FASTER
```

### Question 3

```{r}
n <- 50
mu_true <- 1
B <- 2000
M <- 10000

cl3 <- makeCluster(detectCores() - 1)
registerDoParallel(cl)

coverage_vec <- foreach(m = 1:M, .combine = c) %dopar% {

  x <- rexp(n, rate = 1)

  boot_means <- replicate(B, mean(sample(x, n, replace = TRUE)))

  ci <- quantile(boot_means, probs = c(0.025, 0.975), names = FALSE)

  (ci[1] <= mu_true) && (mu_true <= ci[2])
}

stopCluster(cl3)

mean(coverage_vec)
```

### Question 4

```{r}
library(iterators)

set.seed(1234)

foreach(x = irnorm(3, count = 5), .combine = c) %do% {
  max(x)
}
```

### Question 5

```{r}
library(parallel)

R <- 50000
set.seed(1234)

t_rep <- system.time(replicate(R, replicate(3, max(rnorm(5)))))["elapsed"]

set.seed(1234)
t_for <- system.time(replicate(R,
  foreach(x = irnorm(3, count = 5), .combine = c) %do% max(x)
))["elapsed"]

cl <- makeCluster(detectCores() - 1)
clusterSetRNGStream(cl, 1234)
t_par <- system.time(replicate(R,
  unlist(parLapply(cl, 1:3, function(i) max(rnorm(5))))
))["elapsed"]
stopCluster(cl)

c(replicate = t_rep, foreach = t_for, parLapply = t_par)
```
